### ISSUE TITLE
3.0 breaks existing content color definitions from <3.x

### ISSUE THREAD

**Issue by bernhardberger** [xndbogdan/statamic-bard-text-color#26]
Thanks to the silent renaming of the `attrs.color` key to `attrs.key` this breaks ALL existing content/yaml.

This should never have been renamed and released with 3.0, not sure what's the best strategy to get out of this mess. 

- [ ] A: undo the releases and rename the key back (this would break new 3.4 installs but would allow upgraded installs to not break)
- [ ] B: support both keys (support and maintenance overhead)
- [ ] C: screw any existing install and break any existing content for any installs that come from Statamic <3.4 
- [ ] D: converter for existing content, not sure if Statamic supports such a concept

**Comment by heidkaemper** [comment]
There is a way to handle 'lagacy' Bard content:
https://gist.github.com/jacksleight/9495628eab586117e5d3b3bfb33111c3

So that would be Option D. In my optionion that's the cleanest way to fix the problem. See my PR:
https://github.com/xndbogdan/statamic-bard-text-color/pull/28/files#diff-880b1c433557ee5041807e46794bc734c82eda6ed602b5606202b25691dfe088

**Comment by xndbogdan** [comment]
Hi. I've pushed V3.1.3
https://github.com/xndbogdan/statamic-bard-text-color/releases/tag/v3.1.3
Thank you for your hard work.
Readme has been updated to reflect that.

@bernhardberger Can you please update your PR, as it is conflicting with the main branch that was merged with @heidkaemper 's fix.
